import sys
import os
import json
import time
import uuid
from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException, Request, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, Field, model_validator

from app.config import settings
from app.logging_config import logger, request_id_var
from app.auth import (
    Principal,
    AuthLoginRequest,
    AuthTokenResponse,
    create_access_token,
    get_current_user,
    require_hr
)
from app.agents.orchestrator import orchestrator
from app.memory import memory_store

# Initialize FastAPI App
app = FastAPI(
    title="EmployeeMate",
    description="Production-Ready Dual-Agent Employee AI Assistant with RAG, HR operations & Security Hardening",
    version="1.0.0"
)

# Optional Prometheus Instrumentator
try:
    from prometheus_fastapi_instrumentator import Instrumentator
    Instrumentator().instrument(app).expose(app)
except Exception:
    pass

# Configure CORS Middleware
allowed_origins = [o.strip() for o in settings.cors_origins.split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins if allowed_origins else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request ID & Logging Middleware
@app.middleware("http")
async def logging_request_id_middleware(request: Request, call_next):
    req_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())
    request_id_var.set(req_id)
    start_time = time.time()

    response = await call_next(request)
    latency_ms = (time.time() - start_time) * 1000

    logger.info(
        f"HTTP {request.method} {request.url.path} -> {response.status_code} ({latency_ms:.1f}ms)"
    )
    response.headers["X-Request-ID"] = req_id
    return response


# Request & Response Models
class ChatRequest(BaseModel):
    prompt: Optional[str] = Field(None, max_length=2000, description="User query or instruction", example="What is the WFH policy?")
    message: Optional[str] = Field(None, max_length=2000, description="Alternative field for user query")

    emp_id: Optional[str] = Field(None, description="Optional Employee ID for HR context", example="EMP001")
    employee_id: Optional[str] = Field(None, description="Alternative field for Employee ID")

    actor_role: Optional[str] = Field("EMPLOYEE", description="Role of the user (ignored for auth)", example="EMPLOYEE")
    session_id: Optional[str] = Field(None, description="Optional conversation session ID")
    category: Optional[str] = Field(None, description="Optional explicit metadata category filter")
    history: Optional[List[dict]] = Field(default_factory=list, description="Recent conversation history")

    @model_validator(mode="after")
    def normalize_assessment_fields(self):
        if not self.prompt and self.message:
            self.prompt = self.message

        if not self.emp_id and self.employee_id:
            self.emp_id = self.employee_id

        if not self.prompt:
            raise ValueError("Either 'prompt' or 'message' is required.")

        return self


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Final answer generated by the system")
    sources: List[str] = Field(default_factory=list, description="List of source policy files retrieved by RAG")
    tools_used: List[str] = Field(default_factory=list, description="List of tools/methods executed during request")
    agent_routed: str = Field(..., description="The name of the agent or orchestrator handling the request")
    updated_employees: Optional[List[dict]] = Field(None, description="Live updated employee profiles state")


# Global Exception Handling
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    req_id = request_id_var.get("")
    logger.exception(f"[Unhandled Server Exception] {exc}")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "detail": "An internal server error occurred.",
            "request_id": req_id,
            "type": exc.__class__.__name__
        }
    )


# --- Core Logic Functions ---
def execute_health_check():
    provider = (getattr(settings, "llm_provider", "ollama") or "ollama").lower().strip()
    if provider == "gemini":
        model = getattr(settings, "gemini_model", "gemini-3.6-flash")
    elif provider == "openai":
        model = getattr(settings, "openai_model", "gpt-4o-mini")
    else:
        model = getattr(settings, "lmstudio_model", "gemma4:latest")
    return {
        "status": "healthy",
        "app_env": getattr(settings, "app_env", "production"),
        "vector_store_initialized": orchestrator.knowledge_agent.rag.vector_store is not None,
        "llm_provider": provider,
        "llm_model": model
    }


def execute_get_employees():
    return orchestrator.hr_agent.db.get_all_employees()


def execute_chat(request_payload: ChatRequest, current_user: Optional[Principal] = None):
    if not request_payload.prompt or not request_payload.prompt.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Prompt field cannot be empty."
        )

    try:
        # User principal defaults or overrides
        user_emp = current_user.emp_id if current_user else (request_payload.emp_id or "EMP001")
        user_role = current_user.role if current_user else (request_payload.actor_role or "EMPLOYEE").upper()
        principal = current_user or Principal(emp_id=user_emp, role=user_role)

        # Retrieve server-side history if payload history is empty
        history_to_use = request_payload.history or memory_store.get_history(principal.emp_id, request_payload.session_id)

        result = orchestrator.route_and_execute(
            prompt=request_payload.prompt,
            emp_id=principal.emp_id,
            history=history_to_use,
            principal=principal,
            actor_role=principal.role,
            category=request_payload.category
        )

        # Update server-side memory
        memory_store.add_turn(principal.emp_id, request_payload.session_id, "user", request_payload.prompt)
        memory_store.add_turn(principal.emp_id, request_payload.session_id, "assistant", result["answer"])

        # Filter updated_employees for non-HR callers
        live_employees = orchestrator.hr_agent.db.get_all_employees()["data"]
        if principal.role != "HR":
            live_employees = [e for e in live_employees if e["emp_id"].upper() == principal.emp_id.upper()]

        return ChatResponse(
            answer=result["answer"],
            sources=result.get("sources", []),
            tools_used=result.get("tools_used", []),
            agent_routed=result.get("agent_routed", "Unknown"),
            updated_employees=live_employees
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"[execute_chat Error] {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing chat request: {str(e)}"
        )


# --- Auth Routes ---
@app.post("/auth/login", response_model=AuthTokenResponse, tags=["Authentication"])
async def login(login_req: AuthLoginRequest):
    emp_clean = login_req.emp_id.strip().upper()
    emp_res = orchestrator.hr_agent.db.get_employee_info(emp_clean)
    if emp_res["status"] == "error":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid employee credentials for '{emp_clean}'"
        )

    emp_data = emp_res["data"]
    role = emp_data.get("role", "EMPLOYEE")
    # Assign HR role for EMP002 or HR department
    if emp_clean == "EMP002" or emp_data.get("department") == "HR":
        role = "HR"
    else:
        role = "EMPLOYEE"

    expected_pwd = settings.demo_hr_password if role == "HR" else settings.demo_employee_password
    if login_req.password != expected_pwd:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid employee credentials (incorrect password)"
        )

    token = create_access_token(emp_clean, role)
    return AuthTokenResponse(
        access_token=token,
        token_type="bearer",
        emp_id=emp_clean,
        role=role,
        name=emp_data.get("name", emp_clean)
    )


# --- Standard Routes ---
@app.get("/api/info", tags=["Health"])
async def root():
    return {
        "message": "Welcome to EmployeeMate API",
        "docs": "/docs",
        "health": "/health"
    }


@app.get("/health", tags=["Health"])
async def health_check():
    return execute_health_check()


@app.get("/employees", tags=["Employees"])
async def get_employees(current_user: Principal = Depends(require_hr)):
    """GET /employees - Requires HR role permission."""
    return execute_get_employees()


@app.post("/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK, tags=["Chat Assistant"])
async def chat(request_payload: ChatRequest, current_user: Principal = Depends(get_current_user)):
    """POST /chat Endpoint - Requires valid JWT authentication."""
    return execute_chat(request_payload, current_user=current_user)


@app.post("/chat/stream", tags=["Chat Assistant"])
def chat_stream(request_payload: ChatRequest, current_user: Principal = Depends(get_current_user)):
    """POST /chat/stream Endpoint - True SSE token streaming with JWT authentication."""
    def event_generator():
        try:
            # Check for pure policy queries vs HR queries
            user_emp = current_user.emp_id
            principal = current_user
            history_to_use = request_payload.history or memory_store.get_history(user_emp, request_payload.session_id)

            # Pre-check for prompt injection
            from app.security import detect_prompt_injection, normalize_input
            norm_prompt = normalize_input(request_payload.prompt)
            is_inj, pattern = detect_prompt_injection(norm_prompt)
            if is_inj:
                meta = {
                    "type": "metadata",
                    "sources": [],
                    "tools_used": [],
                    "agent_routed": "Guardrail",
                    "updated_employees": []
                }
                yield f"data: {json.dumps(meta)}\n\n"
                yield f"data: {json.dumps({'type': 'token', 'token': 'I cannot fulfill this request because it violates safety guidelines.'})}\n\n"
                yield "data: [DONE]\n\n"
                return

            # Check if intent routes strictly to RAG or HR
            from app.conversation import rewrite_followup
            from app.rag import get_llm
            standalone = rewrite_followup(norm_prompt, history_to_use, llm=get_llm())
            
            prompt_lower = standalone.lower()
            is_hr_intent = bool("leave" in prompt_lower or "balance" in prompt_lower or "emp" in prompt_lower)

            if not is_hr_intent:
                # Stream RAG query tokens
                for stream_event in orchestrator.knowledge_agent.rag.stream_query(
                    query_text=standalone,
                    category=request_payload.category,
                    emp_id=user_emp,
                    history=history_to_use
                ):
                    yield f"data: {json.dumps(stream_event)}\n\n"
                yield "data: [DONE]\n\n"
                return

            # Synchronous fall-through for HR operations
            res = execute_chat(request_payload, current_user=current_user)
            meta = {
                "type": "metadata",
                "sources": res.sources,
                "tools_used": res.tools_used,
                "agent_routed": res.agent_routed,
                "updated_employees": res.updated_employees
            }
            yield f"data: {json.dumps(meta)}\n\n"
            yield f"data: {json.dumps({'type': 'token', 'token': res.answer})}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as e:
            logger.exception(f"[SSE Stream Error] {e}")
            yield f"data: {json.dumps({'type': 'error', 'error': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


# --- Serverless `/api` Alias Routes ---
@app.get("/api", tags=["Health Serverless"], include_in_schema=False)
async def root_api():
    return await root()


@app.get("/api/health", tags=["Health Serverless"], include_in_schema=False)
async def health_check_api():
    return execute_health_check()


@app.post("/api/auth/login", response_model=AuthTokenResponse, tags=["Authentication Serverless"], include_in_schema=False)
async def login_api(login_req: AuthLoginRequest):
    return await login(login_req)


@app.get("/api/employees", tags=["Employees Serverless"], include_in_schema=False)
async def get_employees_api(current_user: Principal = Depends(require_hr)):
    return await get_employees(current_user=current_user)


@app.post("/api/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK, tags=["Chat Assistant Serverless"], include_in_schema=False)
async def chat_api(request_payload: ChatRequest, current_user: Principal = Depends(get_current_user)):
    return execute_chat(request_payload, current_user=current_user)


@app.post("/api/chat/stream", tags=["Chat Assistant Serverless"], include_in_schema=False)
def chat_stream_api(request_payload: ChatRequest, current_user: Principal = Depends(get_current_user)):
    return chat_stream(request_payload, current_user=current_user)


# --- Static File Serving (React UI Frontend) ---
frontend_dist = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend", "dist")
if os.path.exists(frontend_dist):
    from fastapi.staticfiles import StaticFiles
    app.mount("/", StaticFiles(directory=frontend_dist, html=True), name="static")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)